CREATE TABLE canto_token_transfers (
    value VARCHAR(MAX),
    blockHash VARCHAR(MAX),
    blockNumber VARCHAR(MAX),
    confirmations VARCHAR(MAX),
    contractAddress VARCHAR(MAX),
    cumulativeGasUsed VARCHAR(MAX),
    fromAddress VARCHAR(MAX),
    gas VARCHAR(MAX),
    gasPrice VARCHAR(MAX),
    gasUsed VARCHAR(MAX),
    hash VARCHAR(MAX),
    input VARCHAR(MAX),
    logIndex VARCHAR(MAX),
    nonce VARCHAR(MAX),
    timeStamp VARCHAR(MAX),
    toAddress VARCHAR(MAX),
    tokenDecimal VARCHAR(MAX),
    tokenName VARCHAR(MAX),
    tokenSymbol VARCHAR(MAX),
    transactionIndex VARCHAR(MAX)
);
